### ISSUE TITLE
Bad author mail address

### ISSUE THREAD

**Issue by jmleroux** [DruGento/AkeneoDateCollection#1]
Unless i don't know all my colleagues... ;)

https://github.com/DruGento/AkeneoDateCollection/blob/7f8c9f6386e59c350e578501416b1c2be568149b/src/DataGrid/Extension/Formatter/Property/ProductValue/DateCollectionProperty.php#L13

**Comment by alexdrupal** [comment]
Hello

Yeah, you're right. Thank you!

**Comment by nickby** [comment]
I'm sorry, copy-paste error :) I will fix it soon.
